//**************************//
//**** INDEX.HTML PAGE *****//
//**************************//

// In case new character created, getting the CHARACTER_ID generated by script from create.html and saved into browser local storage

let createdID = localStorage.getItem("createdID");
console.log(createdID);

// General approach: try to declare constants and functions in the same order of the HTML elements that they refer to.

const TARGET = document.getElementById("target");
const TEMPLATE = document.getElementById("tpl-char");

// Defining an async function to get a character by its ID and to display the character in the template element of the index.html page

const displayCreatedChar = async (createdID) => {
  try{
  let response = await fetch(`https://character-database.becode.xyz/characters/:${createdID}`);
  if(!response.ok) {
    throw new Error ("This ID doesn't exist");
  }
  let character = await response.json();

  let clone = TEMPLATE.cloneNode(true).content;

  clone.querySelector(".charmain__img").src = `data:image/jpeg;base64,${character.image}`;
  clone.querySelector(".charmain__title").innerHTML = character.name;
  clone.querySelector(".charmain__bio").innerHTML = character.shortDescription;
  TARGET.appendChild(clone);

  }catch (error){
    console.error(error);
  }
};

